export { test, expect } from './fixtures.js';
export type { ForensicsFixture } from './fixtures.js';
export type { DomNode, SnapshotOptions } from './collector/dom-snapshot.js';
export type { MutationBatch, MutationFlush, MutationLogOptions, MutationRecord } from './collector/mutation-log.js';
export type { ParsedError, ParsedLocator, FailureType } from './analyzer/error-parser.js';
export type { Verdict } from './analyzer/verdict-builder.js';
export type { DiffResult } from './analyzer/dom-diff.js';
export type { SelectorTrace } from './analyzer/selector-tracer.js';
export { parseLocatorExpression } from './analyzer/locator/parser.js';
export { queryLocator } from './analyzer/locator/engine.js';
export type { LocatorExpression, LocatorStep, TextMatcher } from './analyzer/locator/types.js';
export type { LocatorQueryResult } from './analyzer/locator/engine.js';
export { readPlaywrightTrace } from './trace/trace-reader.js';
export type { TraceAction, TraceConsoleEvent, TraceEvidence, TraceNetworkEvent, TraceReaderOptions } from './trace/trace-reader.js';
export { loadConfig } from './config.js';
export type { ForensicsConfig, RedactionConfig, TraceConfig } from './config.js';
export { registerPlugin, loadPlugins, getPlugin } from './plugin.js';
export type { ForensicsPlugin, PluginContext } from './plugin.js';
